import {DemoRiskLedger,guardedDemoOrder} from '../part-one-risk.mjs';
import {createTradeDecision,validateTradeDecision} from '../public/trade-decision.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {analyzeBalance,BalanceBook,BALANCE_MARKETS,assertCandidate,continuationAllowed} from '../public/balance-engine.js';
import {BalanceEvidence} from '../public/balance-scale.js';
import {validateBalanceRequest,validateBalancePurchase,assertProposalBinding} from '../balance-authorization.mjs';
import {PartOneExecution} from '../part-one-execution.mjs';
import {proposalRequest,DigitBarrierEngine} from '../public/digit-barrier-engine.js';
import {TradabilityMarkets} from '../public/tradability-markets.js';
const patterns={'OVER 1':[2,3,7,8,9],'OVER 2':[3,5,7,8,9],'UNDER 8':[7,6,2,1,0],'UNDER 7':[6,4,2,1,0]};
const rows=(p,n=200,end=1000)=>Array.from({length:n},(_,i)=>({digit:p[i%p.length],epoch:end-n+1+i}));
const state=(label,end=1000,market='R_100')=>analyzeBalance(market,rows(patterns[label],200,end));
const request=s=>({decision:createTradeDecision(s.selected,s,{now:s.createdAt}),candidate:s.selected,balanceState:s,decisionId:s.selected.id,type:s.selected.contractType,barrier:s.selected.barrier,symbol:s.market,mode:'auto',stake:1,currency:'USD',authorizePurchase:()=>true});
for(const label of Object.keys(patterns))test(label+' genuinely qualifies with exact immutable mapping',()=>{const s=state(label);assert.equal(s.selected.label,label);assert.equal(s.candidates.length,4);assert.equal(s.selected.checks.filter(c=>c.pass).length,8);assert.ok(Object.isFrozen(s.selected));assertCandidate(s.selected,s,{now:1000000});validateBalanceRequest(request(s),1000000);const p=proposalRequest(request(s));assert.equal(p.contract_type,s.selected.contractType);assert.equal(Number(p.barrier),s.selected.barrier);assertProposalBinding(request(s),p);});
test('mirror symmetry, continuous measurement, neutral/no-trade, all four analyzed without quota',()=>{for(const label of ['OVER 1','OVER 2']){const s=state(label),mirror=analyzeBalance('R_100',s.ticks.map(t=>({...t,digit:9-t.digit})));assert.equal(mirror.position,-s.position);assert.equal(mirror.selected.strength,s.selected.strength);assert.equal(mirror.selected.barrier,9-s.selected.barrier);}const s=analyzeBalance('R_100',rows([0,1,2,3,4,5,6,7,8,9]));assert.equal(s.selected,null);assert.equal(s.lean,'CENTER');const positions=new Set();let h=rows([0,1,2,3,4,5,6,7,8,9]);for(let i=1;i<70;i++){h=[...h,{digit:8,epoch:1000+i}].slice(-200);positions.add(analyzeBalance('R_100',h).position);}assert.ok(positions.size>30);});
test('old analyzer did analyze UNDER symmetrically; only two barriers were generated',()=>{for(const label of ['OVER 1','UNDER 8']){const e=new DigitBarrierEngine();let s;for(let i=1;i<4;i++)s=e.analyze(rows(patterns[label==='OVER 1'?'OVER 2':'UNDER 7']),{sequence:i});assert.equal(s.selected.label,label);assert.deepEqual(s.candidates.map(c=>c.barrier),[1,8]);}});
test('five histories survive inspection and execution switches; duplicates, invalid and stale data rejected',()=>{const b=new BalanceBook();for(const m of BALANCE_MARKETS)for(const t of state('UNDER 7').ticks)b.push(m,t);const originals=[...b.states.values()];b.manual('UNDER',8);b.inspect('R_10');b.executionMarket='R_25';assert.deepEqual([...b.states.values()],originals);assert.deepEqual(b.manualSelection,{direction:'UNDER',barrier:8});assert.equal(b.best(1000000).market,'R_25');assert.equal(b.push('R_25',{digit:NaN,epoch:1001}),null);assert.equal(b.push('R_25',{digit:2,epoch:1000}),null);assert.equal(b.available(b.current().selected,1006000),false);assert.throws(()=>analyzeBalance('R_100',[{digit:4,epoch:1},{digit:5,epoch:1}]));});
test('consumed state cannot repeat; same strength fresh post-settlement evidence can continue; decline blocks',()=>{const b=new BalanceBook();for(const t of state('OVER 2').ticks)b.push('R_100',t);const c=b.current().selected;b.consume(c,1000000);assert.equal(b.available(c,1000000),false);b.settled('R_100',1001000);b.push('R_100',{digit:3,epoch:1001});assert.equal(b.available(b.current().selected,1001000),false);b.push('R_100',{digit:5,epoch:1002});assert.equal(b.available(b.current().selected,1002000),true);const weakened=analyzeBalance('R_100',[...b.current().ticks,{digit:0,epoch:1003}]);assert.equal(weakened.selected,null);assert.equal(continuationAllowed({...c,strength:c.strength-1},state('OVER 2'),{candidate:c,balanceState:state('OVER 2')}),false);});
test('tampering, direction, market, barrier, proposal and expiry all fail closed',()=>{const s=state('UNDER 8'),r=request(s);for(const change of [{type:'DIGITOVER'},{barrier:1},{symbol:'R_25'},{decisionId:'other'},{candidate:{...s.selected,strength:100}},{balanceState:{...s,position:50}}])assert.throws(()=>validateBalanceRequest({...r,...change},1000000));assert.throws(()=>validateBalanceRequest(r,1006000),/EXPIRED|Expired/);assert.throws(()=>assertProposalBinding(r,{...proposalRequest(r),contract_type:'DIGITOVER'}));assert.throws(()=>proposalRequest({...r,barrier:1}));});
test('server pre-BUY observes actual precision and continuous ticks; stale/mismatched/deteriorated rejects',()=>{const s=state('OVER 2'),r=request(s),last=s.ticks.at(-1);assert.equal(validateBalancePurchase(r,{...last,receivedAt:1000000},1000000),true);assert.throws(()=>validateBalancePurchase(r,{...last,digit:0,receivedAt:1000000},1000000),/disagrees/);assert.throws(()=>validateBalancePurchase(r,null,1000000));assert.throws(()=>validateBalancePurchase(r,{digit:3,epoch:1001,receivedAt:1001000},1001000),/continuous/);assert.throws(()=>validateBalancePurchase(r,{digit:0,epoch:1001,receivedAt:1001000,history:[last,{digit:0,epoch:1001}]},1001000),/deteriorated/);assert.equal(validateBalancePurchase(r,{digit:3,epoch:1001,receivedAt:1001000,history:[last,{digit:3,epoch:1001}]},1001000),true);});
class Socket{readyState=1;sent=[];listeners={};addEventListener(n,f){(this.listeners[n]??=[]).push(f);}send(raw){this.sent.push(JSON.parse(raw));}last(k){return this.sent.filter(r=>k in r).at(-1);}reply(req,data){for(const f of this.listeners.message??[])f({data:JSON.stringify({req_id:req.req_id,echo_req:req,...data})});}}
const flush=()=>new Promise(setImmediate),credentials={accountId:'test-demo',accountType:'demo',token:'MOCK'};
for(const label of Object.keys(patterns))test(label+' actual executor: four consecutive proposal/BUY/contract/settlement lifecycles including loss',async()=>{let now=1000000;const socket=new Socket(),events=[],engine=new PartOneExecution({connect:async()=>socket,now:()=>now,log:e=>events.push(e)});for(let i=0;i<4;i++){const s=state(label,now/1000),r={...request(s),attemptId:'balance-'+i},flow=engine.execute(credentials,r);await flush();const tick=socket.last('ticks');socket.reply(tick,{tick:{symbol:s.market,epoch:now/1000,quote:100+s.ticks.at(-1).digit/100,pip_size:2}});const proposal=socket.last('proposal');assert.equal(proposal.contract_type,s.selected.contractType);assert.equal(Number(proposal.barrier),s.selected.barrier);socket.reply(proposal,{proposal:{id:'p'+i,ask_price:1,payout:1.1}});const buy=socket.last('buy');assert.equal(buy.buy,'p'+i);socket.reply(buy,{buy:{contract_id:i+1,buy_price:1}});const entry=await flow.entry;assert.equal(entry.candidate.id,s.selected.id);const monitor=socket.last('proposal_open_contract'),won=i%2===0,digit=won?(s.selected.direction==='OVER'?9:0):(s.selected.direction==='OVER'?0:9);now+=1000;socket.reply(monitor,{proposal_open_contract:{contract_id:i+1,contract_type:s.selected.contractType,barrier:s.selected.barrier,underlying:s.market,entry_tick:100+s.ticks.at(-1).digit/100,exit_tick:100+digit/100,exit_tick_time:now/1000,pip_size:2,is_sold:1,status:won?'won':'lost',profit:won?.1:-1,payout:won?1.1:0}});const result=await flow.settlement;assert.equal(result.type,s.selected.contractType);assert.equal(result.barrier,s.selected.barrier);assert.equal(result.lifecycle.settlementDigit,digit);assert.equal(engine.snapshot(credentials.accountId).state,'IDLE');assert.throws(()=>engine.execute(credentials,{...r,attemptId:'reuse-'+i}),/consumed/);now+=1000;}assert.equal(socket.sent.filter(r=>r.buy).length,4);for(const stage of ['PROPOSAL_RESPONSE_RECEIVED','BUY_RESPONSE_RECEIVED','CONTRACT_ID_RECEIVED','SETTLED','READY_FOR_NEXT_TRADE'])assert.equal(events.filter(e=>e.stage===stage).length,4);});
test('proposal direction mismatch yields zero BUY',async()=>{let now=1000000;const socket=new Socket(),engine=new PartOneExecution({connect:async()=>socket,now:()=>now});const s=state('UNDER 7'),flow=engine.execute(credentials,{...request(s),attemptId:'bad-proposal'});await flush();const p=socket.last('proposal');socket.reply(p,{echo_req:{...p,barrier:'1'},proposal:{id:'bad',ask_price:1,payout:1.1}});await assert.rejects(flow.entry,/AUTHORITATIVE DECISION MISMATCH/);assert.equal(socket.sent.some(r=>r.buy),false);});
test('existing five-market feed passes verified normalized ticks once to balance engine',()=>{const b=new BalanceBook(),feed=new TradabilityMarkets({onTick:t=>b.push(t.market,t)});for(const m of BALANCE_MARKETS){feed.push(m,123.4,1000,2);feed.push(m,123.4,1000,2);assert.equal(b.current(m).ticks.length,1);assert.equal(b.current(m).ticks[0].digit,0);}feed.push('R_100',123.47,1001,undefined);assert.equal(b.current('R_100').ticks.length,1);});
test('trade evidence separates mock from broker; identity mismatch rejected; capacity bounded',()=>{const e=new BalanceEvidence({storage:null}),s=state('UNDER 8');for(let i=0;i<260;i++)e.receipt({...request(s),contractId:i+1,state:'settled',status:i%2?'lost':'won',profit:i%2?-1:.1,evidenceSource:'mock'});assert.equal(e.records.size,250);assert.deepEqual(e.report().groups,{});e.receipt({...request(s),contractId:300,state:'settled',status:'lost',profit:-1});assert.equal(Object.values(e.report().groups)[0].losses,1);e.receipt({...request(s),contractId:301,type:'DIGITOVER',state:'settled',status:'won',profit:1});assert.equal(e.records.has('301'),false);});

test('locked decision cannot be mutated; Manual Explore and market inspection cannot change Auto decision',()=>{const s=state('UNDER 7'),r=request(s),b=new BalanceBook();for(const t of s.ticks)b.push('R_100',t);const original=JSON.stringify(r.decision);b.manual('OVER',1);b.inspect('R_25');b.executionMarket='R_10';assert.equal(JSON.stringify(r.decision),original);assert.throws(()=>{r.decision.candidate.barrier=1;},TypeError);assert.equal(r.decision.candidate.label,'UNDER 7');assert.equal(validateTradeDecision(r.decision,r,1000000,r.decisionId),r.decision);assert.throws(()=>validateTradeDecision(r.decision,r,1000000,'different-active-decision'),e=>e.code==='AUTHORITATIVE_DECISION_MISMATCH');});
test('active decision ID changes while proposal is pending: blocked with no purchase',async()=>{const socket=new Socket(),engine=new PartOneExecution({connect:async()=>socket,now:()=>1000000}),s=state('UNDER 7'),r={...request(s),attemptId:'active-mismatch'},flow=engine.execute(credentials,r);await flush();socket.reply(socket.last('ticks'),{tick:{symbol:'R_100',epoch:1000,quote:100,pip_size:2}});const original=engine.current.bind(engine);engine.current=()=>({request:{decision:{decisionId:'wrong'}}});socket.reply(socket.last('proposal'),{proposal:{id:'p',ask_price:1,payout:1.1}});assert.equal(socket.sent.filter(x=>x.buy).length,0);engine.current=original;await assert.rejects(flow.entry,/AUTHORITATIVE DECISION MISMATCH/);assert.match(engine.snapshot(credentials.accountId).last.error.message,/AUTHORITATIVE DECISION MISMATCH/);});

test('continuation compares clearance at the same barrier when moving from OVER1 to OVER2',()=>{const first=state('OVER 1'),next=state('OVER 2',1002);assert.equal(continuationAllowed(next.selected,next,{candidate:first.selected,balanceState:first}),true);const firstUnder=state('UNDER 8'),nextUnder=state('UNDER 7',1002);assert.equal(continuationAllowed(nextUnder.selected,nextUnder,{candidate:firstUnder.selected,balanceState:firstUnder}),true);});

test('BUY with another proposal ID is blocked before transport send',async()=>{const socket=new Socket(),engine=new PartOneExecution({connect:async()=>socket,now:()=>1000000}),r={...request(state('UNDER 7')),attemptId:'buy-binding-mismatch'},flow=engine.execute(credentials,r);await flush();socket.reply(socket.last('ticks'),{tick:{symbol:'R_100',epoch:1000,quote:100,pip_size:2}});const a=engine.find(credentials.accountId,r.attemptId);a.proposalBinding={candidateId:r.candidate.id,type:r.type,barrier:r.barrier,proposalId:'correct'};assert.throws(()=>engine.send(credentials.accountId,engine.channels.get(engine.key(credentials.accountId)),{buy:'wrong',price:1},{kind:'buy',attemptId:r.attemptId}),e=>e.code==='AUTHORITATIVE_DECISION_MISMATCH');assert.equal(socket.sent.some(r=>r.buy),false);engine.reject(credentials.accountId,a,{code:'TEST_FINISHED',message:'Mock cleanup'});await assert.rejects(flow.entry);});

test('expired pre-proposal decision releases risk reservation; never creates an uncertain purchase lock',async()=>{const ledger=new DemoRiskLedger(),engine=new PartOneExecution({connect:async()=>{throw Error('Must not connect');},now:()=>1006000}),r={...request(state('UNDER 7')),attemptId:'expired-before-proposal'};await assert.rejects(guardedDemoOrder(ledger,credentials.accountId,r,()=>engine.execute(credentials,r)),e=>e.orderNotSubmitted===true);assert.equal(ledger.status(credentials.accountId).pending,null);assert.equal(ledger.status(credentials.accountId).trades,0);assert.equal(engine.snapshot(credentials.accountId).blocking,false);});
