import {test} from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {PartOneExecution} from '../part-one-execution.mjs';
import {DemoRiskLedger,guardedDemoOrder} from '../part-one-risk.mjs';
class FakeSocket {
 readyState=1;listeners={};sent=[];
 addEventListener(n,fn){(this.listeners[n]??=[]).push(fn);}
 send(raw){this.sent.push(JSON.parse(raw));}
 emit(n,data){for(const fn of this.listeners[n]||[])fn(n==='message'?{data:JSON.stringify(data)}:data);}
 close(){this.readyState=3;this.emit('close',{});}
 reply(req,body){this.emit('message',{req_id:req.req_id,echo_req:req,...body});}
 last(kind){return this.sent.filter(r=>Object.hasOwn(r,kind)).at(-1);}
}
const credentials={accountId:'demo-test',accountType:'demo',token:'FAKE-NOT-A-TOKEN'};
const base={authorizePurchase:()=>true,type:'DIGITOVER',symbol:'R_100',stake:1,currency:'USD',mode:'auto'};
const flush=()=>new Promise(setImmediate);
function fixture(options={}){const sockets=[],timers=new Map(),settled=[],logs=[];let now=0,seq=0;
 const config={connect:async()=>{const s=new FakeSocket();sockets.push(s);return s;},now:()=>now,setTimer:fn=>{timers.set(++seq,fn);return seq;},clearTimer:id=>timers.delete(id),onSettled:(id,a,r)=>settled.push(r),log:e=>logs.push(e),...options};
 const engine=new PartOneExecution(config);
 return {engine,config,sockets,timers,settled,logs,get socket(){return sockets.at(-1);},advance:n=>now+=n,expire:async()=>{const [id,fn]=timers.entries().next().value??[];assert.ok(fn,'watchdog armed');timers.delete(id);now+=16000;fn();await flush();}};
}
async function proposed(f,attemptId='attempt-001'){const flow=f.engine.execute(credentials,{...base,attemptId});await flush();const s=f.socket,p=s.last('proposal');assert.ok(p);s.reply(p,{proposal:{id:'proposal-'+attemptId,ask_price:1,payout:1.1}});return {flow,s,buy:s.last('buy')};}
function bought(s,buy,contractId=100){s.reply(buy,{buy:{contract_id:contractId,buy_price:1,transaction_id:contractId+10000}});return s.last('proposal_open_contract');}
function settled(s,monitor,contractId=100,profit=.1,extras={}){s.reply(monitor,{subscription:{id:'sub-'+contractId},proposal_open_contract:{contract_id:contractId,entry_tick:100.12,exit_tick:profit>0?100.15:100.10,is_sold:1,status:profit>0?'won':'lost',profit,payout:profit>0?1.1:0,...extras}});}
test('25 sequential complete lifecycles: matching proposal, BUY, contract, P/L, reset, next order',async()=>{
 const f=fixture();for(let i=1;i<=25;i++){const {flow,s,buy}=await proposed(f,'sequence-'+i);assert.ok(buy);const m=bought(s,buy,i);assert.equal((await flow.entry).contractId,i);settled(s,m,i,i%2?.1:-1);assert.equal((await flow.settlement).contractId,i);assert.equal(f.engine.snapshot(credentials.accountId).state,'IDLE');assert.equal(f.timers.size,0);}
 assert.equal(f.settled.length,25);assert.equal(f.socket.sent.filter(r=>r.buy).length,25);assert.equal(f.socket.sent.filter(r=>r.forget).length,25);assert.equal(f.socket.listeners.message.length,1);assert.ok(f.socket.sent.every(r=>Number.isInteger(r.req_id)));assert.equal(new Set(f.socket.sent.map(r=>r.req_id)).size,f.socket.sent.length);
 for(const stage of ['TRADE_AUTHORIZED','PROPOSAL_PENDING','PROPOSAL_RESPONSE_RECEIVED','PROPOSAL_ID_RECEIVED','BUY_PENDING','BUY_RESPONSE_RECEIVED','CONTRACT_ID_RECEIVED','OPEN_CONTRACT_SUBSCRIPTION_ACTIVE','SETTLED','WIN_LOSS_DETECTED','PROFIT_LOSS_RECORDED','STATE_RESET','READY_FOR_NEXT_TRADE'])assert.equal(f.logs.filter(e=>e.stage===stage).length,25,stage);
});
test('proposal rejection reports full error and releases without BUY',async()=>{const f=fixture(),flow=f.engine.execute(credentials,{...base,attemptId:'reject-proposal'});await flush();const req=f.socket.last('proposal');f.socket.reply(req,{error:{code:'InvalidContractProposal',message:'Proposal rejected'}});await assert.rejects(flow.entry,e=>e.code==='InvalidContractProposal'&&e.orderNotSubmitted);assert.equal(f.socket.sent.filter(r=>r.buy).length,0);assert.equal(f.engine.snapshot(credentials.accountId).blocking,false);const log=f.logs.find(e=>e.stage==='API_ERROR');assert.equal(log.error.echo_req.req_id,req.req_id);});
test('BUY rejection releases lock with error; no automatic retry',async()=>{const f=fixture(),{flow,s,buy}=await proposed(f);s.reply(buy,{error:{code:'PriceMoved',message:'Purchase refused'}});await assert.rejects(flow.entry,e=>e.code==='PriceMoved'&&e.orderNotSubmitted);assert.equal(f.engine.snapshot(credentials.accountId).state,'IDLE');assert.equal(s.sent.filter(r=>r.buy).length,1);});
test('BUY timeout queries account evidence, blocks duplicates; late matching BUY recovers',async()=>{const f=fixture(),{flow,s,buy}=await proposed(f);await f.expire();await assert.rejects(flow.entry,/confirmed/);assert.equal(f.engine.snapshot(credentials.accountId).state,'RECONCILIATION_REQUIRED');assert.ok(s.last('portfolio'));assert.ok(s.last('statement'));assert.equal(s.sent.filter(r=>r.buy).length,1);assert.throws(()=>f.engine.execute(credentials,{...base,attemptId:'another-attempt'}),/already active/);const m=bought(s,buy,9);settled(s,m,9);await flow.settlement;assert.equal(f.engine.snapshot(credentials.accountId).state,'IDLE');});
test('disconnect before BUY: explicit rejection and reusable engine',async()=>{const f=fixture(),flow=f.engine.execute(credentials,{...base,attemptId:'before-disconnect'});await flush();f.socket.close();await assert.rejects(flow.entry,e=>e.orderNotSubmitted);assert.equal(f.engine.snapshot(credentials.accountId).blocking,false);assert.equal(f.socket.sent.filter(r=>r.buy).length,0);});
test('disconnect after BUY with known contract restores monitoring, not BUY',async()=>{const f=fixture(),{flow,s,buy}=await proposed(f);bought(s,buy,22);await flow.entry;s.close();await flush();assert.equal(f.sockets.length,2);const m=f.socket.last('proposal_open_contract');assert.equal(m.contract_id,22);assert.equal(f.socket.sent.filter(r=>r.buy).length,0);settled(f.socket,m,22);await flow.settlement;assert.equal(f.engine.snapshot(credentials.accountId).state,'IDLE');});
test('disconnect after BUY before confirmation stays explicitly unresolved, not falsely READY',async()=>{const f=fixture(),{flow,s}=await proposed(f);s.close();await flush();await assert.rejects(flow.entry);assert.equal(f.engine.snapshot(credentials.accountId).blocking,true);assert.equal(f.sockets.flatMap(s=>s.sent).filter(r=>r.buy).length,1);});
test('missing settlement watchdog re-subscribes exact contract and accepts late settlement once',async()=>{const f=fixture(),{flow,s,buy}=await proposed(f);const old=bought(s,buy,33);await flow.entry;s.reply(old,{subscription:{id:'old-sub'},proposal_open_contract:{contract_id:33,is_sold:0,entry_tick:100.12,status:'open'}});await f.expire();const m=s.last('proposal_open_contract');assert.notEqual(m.req_id,old.req_id);assert.equal(m.contract_id,33);settled(s,m,33);settled(s,old,33);settled(s,m,33);await flow.settlement;assert.equal(f.settled.length,1);assert.equal(s.sent.filter(r=>r.buy).length,1);});
test('old contract response and unrelated subscription error cannot affect next trade',async()=>{const f=fixture(),first=await proposed(f,'first-attempt'),m1=bought(first.s,first.buy,1);settled(first.s,m1,1);await first.flow.settlement;const second=await proposed(f,'second-attempt'),m2=bought(second.s,second.buy,2);settled(second.s,m1,1,-1);settled(second.s,m2,1,-1);second.s.emit('message',{req_id:999999,error:{code:'Unrelated',message:'Not this order'}});assert.equal(f.engine.snapshot(credentials.accountId).blocking,true);assert.equal(f.settled.length,1);settled(second.s,m2,2);await second.flow.settlement;assert.equal(f.settled.length,2);});
test('duplicate signal/BUY/proposal messages cannot create a second purchase',async()=>{const f=fixture(),{flow,s,buy}=await proposed(f);const duplicate=f.engine.execute(credentials,{...base,attemptId:'attempt-001'});assert.equal(flow.entry,duplicate.entry);s.reply(s.last('proposal'),{proposal:{id:'duplicate',ask_price:1,payout:1.1}});const m=bought(s,buy,45);bought(s,buy,45);settled(s,m,45);await flow.settlement;assert.equal(s.sent.filter(r=>r.buy).length,1);assert.equal(f.settled.length,1);});
test('stale warmed proposal ignored; invalid fresh proposal rejected before purchase',async()=>{const f=fixture();await f.engine.prepare(credentials,base);const req=f.socket.sent.find(r=>r.proposal&&r.contract_type==='DIGITOVER');f.socket.reply(req,{proposal:{id:'old',ask_price:1,payout:1.1},subscription:{id:'warm-sub'}});f.advance(6000);const flow=f.engine.execute(credentials,{...base,attemptId:'stale-attempt'});await flush();const fresh=f.socket.last('proposal');assert.ok(!fresh.subscribe);f.socket.reply(fresh,{proposal:{id:'bad',ask_price:2,payout:3}});await assert.rejects(flow.entry,e=>e.code==='INVALID_PROPOSAL');assert.equal(f.socket.sent.filter(r=>r.buy).length,0);});
test('settlement without entry quote still completes instead of leaving HTTP entry unresolved',async()=>{const f=fixture(),{flow,s,buy}=await proposed(f);const m=bought(s,buy,55);assert.equal((await flow.entry).contractId,55);settled(s,m,55,.1,{entry_tick:undefined,exit_tick:undefined});await flow.settlement;assert.equal(f.engine.snapshot(credentials.accountId).state,'IDLE');assert.equal(f.engine.receipt(credentials.accountId).entryTick,null);});
test('restart recovers known contract from durable journal without a new purchase',async()=>{const file=join(mkdtempSync(join(tmpdir(),'execution-restart-')),'journal.json'),f=fixture({file}),{flow,s,buy}=await proposed(f,'restart-attempt');bought(s,buy,66);await flow.entry;const resumed=fixture({file});await resumed.engine.resume(credentials);const m=resumed.socket.last('proposal_open_contract');assert.equal(m.contract_id,66);settled(resumed.socket,m,66);assert.equal(resumed.engine.snapshot(credentials.accountId).state,'IDLE');assert.equal(resumed.socket.sent.filter(r=>r.buy).length,0);assert.ok(!readFileSync(file,'utf8').includes(credentials.token));});
test('restart with unknown BUY never sends another purchase',async()=>{const file=join(mkdtempSync(join(tmpdir(),'execution-unknown-')),'journal.json'),f=fixture({file});await proposed(f,'unknown-attempt');const resumed=fixture({file});await resumed.engine.resume(credentials);assert.equal(resumed.engine.snapshot(credentials.accountId).blocking,true);assert.equal(resumed.socket.sent.filter(r=>r.buy).length,0);});
test('stop/restart Auto does not cancel or resubmit an open contract',async()=>{const f=fixture(),{flow,s,buy}=await proposed(f,'stopped-attempt');const m=bought(s,buy,77);await flow.entry;await f.engine.resume(credentials);assert.equal(s.sent.filter(r=>r.buy).length,1);settled(s,m,77);await flow.settlement;assert.equal(f.engine.snapshot(credentials.accountId).state,'IDLE');});
test('risk reservation clears after reconciled settlement, but stays for genuinely unknown BUY',async()=>{const ledger=new DemoRiskLedger(),f=fixture({onSettled:(id,a,r)=>{const p=ledger.status(id).pending;if(p?.attemptId===a.attemptId)ledger.settle(id,p.id,r);}}),request={...base,mode:'manual',attemptId:'risk-recovery'};
 const flow=await guardedDemoOrder(ledger,credentials.accountId,request,()=>f.engine.execute(credentials,request));await flush();const s=f.socket;s.reply(s.last('proposal'),{proposal:{id:'p',ask_price:1,payout:1.1}});const m=bought(s,s.last('buy'),88);await flow.entry;await f.expire();settled(s,s.last('proposal_open_contract'),88);await flow.settlement;assert.equal(ledger.status(credentials.accountId).pending,null);assert.equal(ledger.status(credentials.accountId).trades,1);
});
test('accounting failure is visible and read-only recheck records settlement before releasing lock',async()=>{
 let fail=true,recorded=0;const f=fixture({onSettled:()=>{if(fail)throw Error('Ledger unavailable');recorded++;}}),{flow,s,buy}=await proposed(f,'accounting-recovery');
 const m=bought(s,buy,99);await flow.entry;settled(s,m,99);
 assert.equal(f.engine.snapshot(credentials.accountId).state,'RECONCILIATION_REQUIRED');assert.equal(f.engine.receipt(credentials.accountId).state,'unresolved');
 assert.equal(f.engine.snapshot(credentials.accountId).last.error.code,'ACCOUNTING_FAILED');
 fail=false;await f.engine.resume(credentials,true);await flow.settlement;
 assert.equal(recorded,1);assert.equal(f.engine.snapshot(credentials.accountId).state,'IDLE');assert.equal(s.sent.filter(r=>r.buy).length,1);
});
