import {test} from 'node:test';
import assert from 'node:assert/strict';
import {PartOneExecution} from '../part-one-execution.mjs';
import {resetExecution,purchasePermission} from '../execution-permission.mjs';
const flush=()=>new Promise(setImmediate);
test('permission diagnostics distinguish stale signal from stopped Auto without weakening checks',()=>{const f=fixture();start(f);const p=purchasePermission(f.session,{...request,signalAt:0},f.now);assert.equal(p(),false);assert.match(p.failureReason(),/timestamp/);const q=start(f);f.session.autoControl.running=false;assert.equal(q(),false);assert.match(q.failureReason(),/stopped/);});
class Socket{readyState=1;sent=[];listeners={};addEventListener(n,f){(this.listeners[n]??=[]).push(f);}send(x){this.sent.push(JSON.parse(x));}reply(req,data){for(const f of this.listeners.message??[])f({data:JSON.stringify({req_id:req.req_id,...data})});}close(){this.readyState=3;for(const f of this.listeners.close??[])f();}}
const credentials={accountId:'demo',accountType:'demo'};
const request={attemptId:'safety-attempt',type:'DIGITOVER',symbol:'R_100',stake:1,currency:'USD',mode:'auto',accountId:'demo',strategy:'OVER_UNDER',executionSessionId:'new-session',decisionId:'signal-1',signalAt:1000,gatePassed:true};
function fixture(){let time=1000;const socket=new Socket(),logs=[],session={expiresAt:100000};resetExecution(session);const engine=new PartOneExecution({connect:async()=>socket,now:()=>time,setTimer:()=>0,clearTimer(){},log:e=>logs.push(e),onDisconnect:()=>resetExecution(session)});return {engine,socket,logs,session,now:()=>time,advance:n=>time+=n};}
function start(f){f.session.autoControl={running:true,live:true,accountId:'demo',runId:'new-session',overUnder:true,startedAt:1000};return purchasePermission(f.session,request,f.now);}
test('OFF account connect/resume is passive: zero proposals, buys and contracts',async()=>{const f=fixture();await f.engine.resume(credentials);await f.engine.channel(credentials);await flush();assert.deepEqual(f.socket.sent,[]);assert.equal(f.engine.current('demo'),null);});
test('missing authorization rejects accidental execute and direct BUY transport',async()=>{const f=fixture();const flow=f.engine.execute(credentials,request);await assert.rejects(flow.entry,/permission/);assert.equal(f.socket.sent.length,0);assert.throws(()=>f.engine.send('demo',{ws:f.socket},{buy:'rogue',price:1}),/PURCHASE BLOCKED/);assert.ok(f.logs.some(e=>e.stage==='PURCHASE BLOCKED'));});
for(const reason of ['reload','account reconnect','stop','Auto disabled','new session','disconnect'])test(`${reason} revokes delayed proposal and prior signal`,async()=>{const f=fixture(),authorizePurchase=start(f);const flow=f.engine.execute(credentials,{...request,authorizePurchase});await flush();const p=f.socket.sent.find(r=>r.proposal);assert.ok(p);resetExecution(f.session);f.socket.reply(p,{proposal:{id:'stale',ask_price:1,payout:1.1}});await assert.rejects(flow.entry);assert.equal(f.socket.sent.filter(r=>r.buy).length,0);assert.equal(authorizePurchase(),false);});
test('expired signal and websocket reconnect cannot purchase',async()=>{const f=fixture(),authorizePurchase=start(f);f.advance(5001);assert.equal(authorizePurchase(),false);const flow=f.engine.execute(credentials,{...request,authorizePurchase});await assert.rejects(flow.entry);assert.equal(f.socket.sent.length,0);});
test('valid current session buys once; socket disconnect revokes that session',async()=>{const f=fixture(),authorizePurchase=start(f);f.engine.execute(credentials,{...request,authorizePurchase});await flush();const p=f.socket.sent.find(r=>r.proposal);f.socket.reply(p,{proposal:{id:'valid',ask_price:1,payout:1.1}});assert.equal(f.socket.sent.filter(r=>r.buy).length,1);f.socket.close();assert.equal(authorizePurchase(),false);});
test('fresh server cannot restore active permission; failed gate/session/feed all block',()=>{for(const change of [{executionSessionId:'old'},{gatePassed:false},{decisionId:null},{signalAt:0}]){const f=fixture();start(f);assert.equal(purchasePermission(f.session,{...request,...change},f.now)(),false);}const f=fixture();assert.equal(purchasePermission(f.session,request,f.now)(),false);start(f);f.session.autoControl.live=false;assert.equal(purchasePermission(f.session,request,f.now)(),false);});
test('manual needs fresh single-use intent, independent of Auto',()=>{const f=fixture(),r={...request,mode:'manual',executionSessionId:'manual-intent'};assert.equal(purchasePermission(f.session,r,f.now)(),false);f.session.manualIntent={id:'manual-intent',attemptId:r.attemptId,accountId:'demo',type:r.type,expiresAt:5000};const permit=purchasePermission(f.session,r,f.now);assert.equal(permit(),true);assert.equal(purchasePermission(f.session,r,f.now)(),false);resetExecution(f.session);assert.equal(permit(),false);});
