import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {RiseFallEngine,configuration,DEFAULTS} from '../public/rise-fall/engine.js';
import {PRESETS,presetConfig,presetName} from '../public/rise-fall/presets.js';
import {explain} from '../public/rise-fall/diagnostics.js';
import {RiseFallService,fingerprint} from '../rise-fall-service.mjs';
const epoch=1800000000;
function run(config,mode='trend'){const e=new RiseFallEngine('R_100',config);let quote=1000;for(let i=0;i<600;i++){quote+=mode==='chop'?(i%2?-.1:.1):mode==='flat'?0:i%5===0?-.01:.1;e.add({quote,epoch:epoch+i*2});}return {e,a:e.snapshot((epoch+1198)*1000)};}
test('Original remains default; exploration changes only five explicit thresholds',()=>{assert.deepEqual(presetConfig('original'),DEFAULTS);assert.equal(DEFAULTS.chopFilter,true);assert.equal(presetName(presetConfig('exploration',false)),'exploration');assert.deepEqual(Object.keys(PRESETS.exploration).filter(k=>PRESETS.exploration[k]!==DEFAULTS[k]).sort(),['confidence','minEfficiency','minPersistence','minStrength','pressure'].sort());assert.throws(()=>presetConfig('unknown'));for(const v of ['false',0,null])assert.throws(()=>configuration({chopFilter:v}));});
test('Chop OFF removes only its hard gate, preserving market measurement and confidence',()=>{const config={...DEFAULTS,maxChop:0};const on=run(config).a,off=run({...config,chopFilter:false}).a;assert.ok(on.chop>0);assert.equal(on.marketState,'CHOPPY');assert.equal(on.winner,null);assert.equal(off.winner.type,'CALL');assert.equal(off.chop,on.chop);assert.equal(off.marketState,on.marketState);for(let i=0;i<2;i++){assert.equal(off.candidates[i].confidence,on.candidates[i].confidence);assert.deepEqual(off.candidates[i].checks,{...on.candidates[i].checks,chop:true});}const detail=explain(off,(epoch+1198)*1000)[0];assert.equal(detail.total,14);assert.equal(detail.passed,14);assert.equal(detail.rows.find(r=>r.gate==='chop').disabled,true);});
test('Exploration with chop OFF still blocks sideways, flat and stale data',()=>{const config=presetConfig('exploration',false);for(const mode of ['chop','flat'])assert.equal(run(config,mode).a.winner,null);const {e}=run(config);assert.equal(e.snapshot((epoch+1220)*1000).winner,null);assert.ok(run(config).a.winner);});
test('Replay authorization distinguishes every preset and toggle; old default evidence remains compatible',()=>{const old=JSON.parse(readFileSync('outputs/rise-fall-replay-report.json','utf8'));const baseline=old.profiles.find(p=>p.name==='baseline');assert.equal(fingerprint(baseline.config),fingerprint(DEFAULTS));const values=[presetConfig('original'),presetConfig('original',false),presetConfig('exploration'),presetConfig('exploration',false)];assert.equal(new Set(values.map(fingerprint)).size,4);const service=new RiseFallService({validationFile:'outputs/rise-fall-replay-report.json'});assert.equal(service.validation(DEFAULTS,'R_100',5,'t'),true);assert.equal(service.validation({...PRESETS.exploration,confidence:59},'R_100',5,'t'),false);});
test('Exploration mock purchase settles once; stop, heartbeat and account lock remain effective',async()=>{
 const now=(epoch+1198)*1000,config=presetConfig('exploration',false);
 for(const block of [null,'stop','heartbeat','lock']){const {e}=run(config),calls=[];const service=new RiseFallService({now:()=>now,otherBusy:()=>block==='lock'});service.validation=()=>true;
 const c={owner:'o',id:'s',account:{account_id:'demo1',account_type:'demo',currency:'USD'},session:{expiresAt:now+60000},symbol:'R_100',config,engine:e,contracts:['CALL','PUT'].map(contract_type=>({contract_type,min:{value:1,unit:'t'},max:{value:10,unit:'t'}})),contractsAt:now,used:new Set(),running:true,runId:'run',heartbeat:now-(block==='heartbeat'?30000:0),order:{stake:1,duration:5,unit:'t'},rpc:{closed:false,request:async q=>{calls.push(q);if(q.proposal){if(block==='stop')service.stop('o');return {echo_req:q,proposal:{id:'p',ask_price:1,payout:1.9}};}if(q.buy)return {buy:{contract_id:123,buy_price:1}};return {proposal_open_contract:{contract_id:123,is_sold:1,status:'lost',profit:-1,entry_tick:1045,exit_tick:1044}};}}};service.contexts.set('o',c);await service.maybeExecute(c);await service.maybeExecute(c);assert.equal(calls.filter(q=>q.buy).length,block?0:1);if(!block)assert.equal(service.journal[0].state,'SETTLED');}
});
