import test,{after} from 'node:test';
import {writeFileSync} from 'node:fs';
const proof=[];after(()=>{if(process.env.RF_V2_PROOF_OUTPUT)writeFileSync(process.env.RF_V2_PROOF_OUTPUT,JSON.stringify({execution:'Controlled mocks only; no authenticated Deriv BUY',proof},null,2));});
import assert from 'node:assert/strict';
import {RiseFallEngine,analyze} from '../public/rise-fall/engine.js';
import {presetConfig} from '../public/rise-fall/presets.js';
import {RiseFallService} from '../rise-fall-service.mjs';
import {scanAnalysis} from '../rise-fall-market-selection.mjs';
import {explain} from '../public/rise-fall/diagnostics.js';
const startEpoch=1800000000;
function fixture(sign=1){let epoch=startEpoch,q=1000;const engine=new RiseFallEngine('R_100',presetConfig('balancedV2'));
 for(let i=0;i<300;i++){q+=sign*.1;engine.add({epoch:++epoch,quote:q},{live:false});}
 const now=()=>epoch*1000,read=()=>engine.snapshot(now()),add=(d=sign*.1,options={})=>{q+=d;engine.add({epoch:++epoch,quote:q},options);return read();};
 return {engine,now,read,add,arm:()=>engine.arm('test-'+epoch)};
}
function serviceHarness(f,{duringProposal=()=>{},loss=false}={}){const calls=[],service=new RiseFallService({now:f.now,validationFile:'outputs/rise-fall-replay-report.json'});
 const c={owner:'o',id:'s',account:{account_id:'demo',account_type:'demo',currency:'USD'},session:{expiresAt:f.now()+86400000},symbol:'R_100',config:f.engine.config,engine:f.engine,contracts:['CALL','PUT'].map(contract_type=>({contract_type,min:{value:1,unit:'t'},max:{value:10,unit:'t'}})),contractsAt:f.now(),used:new Set(),running:false,heartbeat:f.now(),rpc:{closed:false,request:async q=>{calls.push(q);if(q.proposal){await duringProposal();return {echo_req:q,proposal:{id:'p',ask_price:1,payout:1.9}};}if(q.buy)return {buy:{contract_id:calls.filter(x=>x.buy).length,buy_price:1}};return {proposal_open_contract:{contract_id:q.contract_id,is_sold:1,status:loss?'lost':'won',profit:loss?-1:.9}};}}};service.contexts.set('o',c);
 return {c,calls,service,start:()=>service.start('o',{sessionId:'s',stake:1,duration:5,unit:'t',demoLimits:{mode:'unlimited'}}),step:async()=>{c.heartbeat=f.now();c.contractsAt=f.now();await service.maybeExecute(c);}};
}
test('Arming favorable history does not authorize a trade; polls cannot manufacture live observations',async()=>{const f=fixture(),h=serviceHarness(f);assert.ok(analyze(f.engine.history,presetConfig('balanced'),f.now()).winner);assert.equal(analyze(f.engine.history,f.engine.config,f.now()).winner,null);h.start();for(let i=0;i<100;i++){h.service.status('o');await h.step();}assert.equal(h.calls.length,0);assert.equal(f.read().confirmation.liveObservations,0);assert.equal(f.read().state,'OBSERVING');for(let i=0;i<19;i++){f.add();await h.step();}assert.equal(h.calls.length,0);assert.equal(f.read().confirmation.liveObservations,19);proof.push({scenario:'startup with favorable history',historicalV1Ready:true,liveObservations:19,brokerRequests:h.calls.length,status:f.read().confirmation.state});});
test('Clean mirrored directions pass OBSERVING, FORMING, CONFIRMED, ENTRY BUILDING then READY',()=>{for(const sign of [1,-1]){const f=fixture(sign);f.arm();const states=[];let first;for(let i=1;i<=40;i++){const a=f.add();states.push(a.confirmation.state);if(a.winner&&!first)first={i,a};}assert.equal(first.i,32);assert.equal(first.a.winner.sign,sign);for(const state of ['OBSERVING',sign===1?'RISE FORMING':'FALL FORMING',sign===1?'RISE CONFIRMED':'FALL CONFIRMED','ENTRY BUILDING','READY'])assert.ok(states.includes(state),state);assert.equal(first.a.confirmation.readyObservations,2);assert.equal(explain(first.a,f.now()).length,2);assert.equal(first.a.confirmation.candidate.observations['ENTRY BUILDING'],1);proof.push({scenario:sign===1?'clean RISE':'clean FALL',firstReadyAtObservation:first.i,states,confirmation:first.a.confirmation,metrics:first.a.winner.balanced.metrics});}});
test('Alternation and isolated positive/negative spikes cannot produce READY',()=>{for(const spike of [0,4,-4]){const f=fixture();f.arm();let ready=0;for(let i=0;i<100;i++){const a=f.add(i===25?spike:i%2?.1:-.1);ready+=!!a.winner;}assert.equal(ready,0);}});
test('A forming trend that deteriorates or reverses loses all accumulated confirmation',()=>{for(const sign of [1,-1]){const f=fixture(sign);f.arm();for(let i=0;i<26;i++)f.add();assert.equal(f.read().confirmation.directionBlocks,1);const states=[];for(let i=0;i<7;i++)states.push(f.add(-sign*.5));assert.ok(states.some(a=>['WEAKENING','REVERSAL RISK','NO DIRECTION'].includes(a.state)));assert.ok(states.every(a=>!a.winner));assert.equal(f.read().confirmation.readyObservations,0);}});
test('Exhausting historical trend cannot be inherited after arming',()=>{const f=fixture();f.arm();for(let i=0;i<40;i++){const a=f.add(i<8?.01:-.08);assert.notEqual(a.winner?.type,'CALL');}});
test('READY lost during proposal cancels before BUY and preserves execution protections',async()=>{const f=fixture(),h=serviceHarness(f,{duringProposal:()=>{for(let i=0;i<3;i++)f.add(-.5);}});h.start();for(let i=0;i<32;i++)f.add();assert.ok(f.read().winner);await h.step();assert.equal(h.calls.filter(q=>q.buy).length,0);assert.equal(h.service.journal[0].state,'REJECTED');assert.equal(h.c.running,true);assert.match(h.service.journal[0].error,/Setup no longer qualifies|signal episode changed/);});
test('Settled trade consumes the event; persistent trend cannot refire, renewed continuation can',async()=>{for(const loss of [false,true]){const f=fixture(),h=serviceHarness(f,{loss});h.start();for(let i=0;i<32;i++)f.add();await h.step();assert.equal(h.service.journal[0].state,'SETTLED');assert.equal(h.service.journal[0].entryAnalysis.confirmation.readyObservations,2);for(let i=0;i<70;i++){f.add();await h.step();}assert.equal(h.calls.filter(q=>q.buy).length,1);for(let i=0;i<12;i++){f.add(-.15);await h.step();}for(let i=0;i<80;i++){f.add(.15);await h.step();}assert.ok(h.calls.filter(q=>q.buy).length>=2);assert.equal(h.c.running,true);proof.push({scenario:loss?'loss then renewed continuation':'win then renewed continuation',orders:h.service.journal,events:f.engine.trend.events});assert.notEqual(h.service.journal[0].signalId,h.service.journal[1].signalId);}});
test('Duplicate ticks, historical backfill, stale ticks and feed gaps do not count as confirmation',()=>{const f=fixture();f.arm();for(let i=0;i<32;i++)f.add();assert.ok(f.read().winner);const before=f.read().confirmation.liveObservations;f.engine.add(f.engine.history.at(-1));assert.equal(f.read().confirmation.liveObservations,before);f.add(.1,{live:false});assert.equal(f.read().confirmation.liveObservations,0);assert.equal(f.read().winner,null);for(let i=0;i<32;i++)f.add();assert.ok(f.read().winner);assert.equal(f.engine.snapshot(f.now()+11000).winner,null);const last=f.engine.history.at(-1);f.engine.add({epoch:last.epoch+20,quote:last.quote+.1});assert.equal(f.engine.snapshot((last.epoch+20)*1000).confirmation.liveObservations,1);const g=fixture();g.arm();g.add(.1,{receivedAt:g.now()+60000});assert.equal(g.read().confirmation.liveObservations,0);});
test('Restart and scanner cache invalidate READY without waiting for another tick',()=>{const f=fixture();f.arm();for(let i=0;i<32;i++)f.add();const row={engine:f.engine};assert.ok(scanAnalysis(row,f.now()).winner);f.engine.arm('new-run');assert.equal(scanAnalysis(row,f.now()).winner,null);assert.equal(scanAnalysis(row,f.now()).confirmation.liveObservations,0);});
test('Minimum observation requirements chosen by transient rejection, not winning outcomes',()=>{const outcomes=[];for(const required of [1,2,3,4]){const f=fixture();f.engine.trend.policy.readyObservations=required;f.arm();for(let i=0;i<31;i++)f.add();outcomes.push({required,oneEligibleObservationReady:!!f.read().winner});f.add(-.6);assert.equal(f.read().winner,null);}assert.deepEqual(outcomes.map(x=>x.oneEligibleObservationReady),[true,false,false,false]);});
test('Two independent direction blocks reject a one-block burst; one block would confirm it',()=>{const confirmed=[];for(const blocks of [1,2]){const f=fixture();f.engine.trend.policy.directionBlocks=blocks;f.arm();for(let i=0;i<25;i++)f.add();confirmed.push(f.read().confirmation.totals.confirmed);for(let i=0;i<5;i++)f.add(-.5);assert.equal(f.read().winner,null);}assert.deepEqual(confirmed,[1,0]);});
test('Opposing medium history is context, while current micro and short direction must agree',()=>{const f=fixture(-1);f.arm();let first;for(let i=0;i<100;i++){const a=f.add(.1);if(a.winner&&!first)first=a;}assert.ok(first);assert.equal(first.winner.type,'CALL');assert.ok(first.winner.balanced.metrics.mediumPressure<50);assert.ok(first.winner.balanced.metrics.shortPressure>50);});
test('Automatic-market arming resets every scanner engine, including cached READY results',async()=>{const f=fixture(),g=fixture(-1);g.engine.symbol='R_25';for(const x of [f,g]){x.arm();for(let i=0;i<32;i++)x.add();assert.ok(x.read().winner);}const h=serviceHarness(f);h.c.autoSelect=true;h.c.marketScan={loading:false,error:null,rows:new Map([f,g].map(x=>[x.engine.symbol,{symbol:x.engine.symbol,name:x.engine.symbol,engine:x.engine,contracts:h.c.contracts,contractsAt:f.now(),verifiedDurations:[{duration:5,unit:'t'}],feedHealth:{subscribed:true,state:'live'}}]))};for(const row of h.c.marketScan.rows.values())assert.ok(scanAnalysis(row,f.now()).winner);h.start();for(const row of h.c.marketScan.rows.values()){assert.equal(scanAnalysis(row,f.now()).winner,null);assert.equal(row.engine.trend.live,0);}await h.step();assert.equal(h.calls.length,0);});
test('V2 demo replay authorizes only tested markets and duration; stale IDs cannot consume READY',()=>{const service=new RiseFallService({validationFile:'outputs/rise-fall-replay-report.json'});for(const symbol of ['R_10','R_25','R_100','1HZ100V','JD10','JD100','stpRNG','stpRNG2'])assert.deepEqual(service.verifiedDurations(presetConfig('balancedV2'),symbol),[{duration:5,unit:'t'}]);assert.equal(service.validation(presetConfig('balancedV2'),'R_100',10,'t'),false);assert.equal(service.validation(presetConfig('balancedV2'),'R_50',5,'t'),false);assert.equal(service.validation(presetConfig('balanced'),'R_100',5,'t'),true);const f=fixture();f.arm();for(let i=0;i<32;i++)f.add();assert.equal(f.engine.consume('stale-id'),false);assert.ok(f.read().winner);});
