import test from 'node:test';
import assert from 'node:assert/strict';
import {RiseFallEngine} from '../public/rise-fall/engine.js';
import {presetConfig} from '../public/rise-fall/presets.js';
import {explain} from '../public/rise-fall/diagnostics.js';
import {RiseFallService} from '../rise-fall-service.mjs';
const base=1800000000;
function sequence(sign=1){const e=new RiseFallEngine('R_100',presetConfig('balanced'));let q=1000;for(let i=0;i<260;i++){q+=i%2?.1:-.1;e.add({epoch:base+i,quote:q});}return {e,add:(d)=>{q+=d;e.add({epoch:base+e.sequence,quote:q});return e.snapshot((base+e.sequence-1)*1000);}};}
test('Balanced mirrored trends progress to READY without maximum historical confirmation',()=>{for(const sign of [1,-1]){const {e,add}=sequence();const states=new Set();let first;for(let i=0;i<70;i++){const a=add(sign*.12);const side=a.candidates.find(c=>c.sign===sign);states.add(side.balanced.state);if(a.winner&&!first)first={i,a};}assert.ok(first);assert.ok(first.i<50);assert.equal(first.a.winner.sign,sign);assert.ok(states.has('WATCH')||states.has('BUILDING'));assert.ok(first.a.winner.balanced.metrics.mediumPressure<65);assert.equal(explain(first.a,(base+e.sequence-1)*1000)[sign===1?0:1].total,10);}});
test('Balanced blocks alternating, stale, reversed and exhausted sequences',()=>{const {e,add}=sequence();assert.equal(e.snapshot((base+259)*1000).winner,null);for(let i=0;i<80;i++)add(.1);assert.equal(e.snapshot((base+e.sequence+30)*1000).winner,null);let exhausted=false;for(let i=0;i<8;i++){const a=add(-.15);exhausted ||= a.candidates[0].balanced.state==='EXHAUSTED';if(i>=4)assert.notEqual(a.winner?.type,'CALL');}assert.ok(exhausted);});
test('A single spike cannot override conflict; prices and directions scale symmetrically',()=>{
 const {add}=sequence();assert.equal(add(3).winner,null);
 const engines=[1,100,-1].map(scale=>({scale,e:new RiseFallEngine('R_100',presetConfig('balanced'))}));let p=0;
 for(let i=0;i<400;i++){p+=i<260?(i%2?.1:-.1):i%5? .12:-.02;const readings=engines.map(({scale,e})=>{e.add({quote:10000+scale*p,epoch:base+i});return e.snapshot((base+i)*1000);});if(i>=260){assert.ok(readings.every(a=>a.candidates.filter(c=>c.ready).length<=1));assert.ok(Math.abs(readings[0].candidates[0].confidence-readings[1].candidates[0].confidence)<1e-6);assert.ok(Math.abs(readings[0].candidates[0].confidence-readings[2].candidates[1].confidence)<1e-6);}}
});
test('Balanced purchase revalidation cancels deterioration during proposal and records lifecycle metrics',async()=>{for(const deteriorate of [false,true]){const {e,add}=sequence();for(let i=0;i<80;i++)add(.1);const now=()=> (base+e.sequence-1)*1000,service=new RiseFallService({now});service.validation=()=>true;const calls=[];const c={owner:'x',id:'x',account:{account_id:'demo',account_type:'demo',currency:'USD'},session:{expiresAt:now()+60000},symbol:'R_100',config:e.config,engine:e,contracts:['CALL','PUT'].map(contract_type=>({contract_type,min:{value:1,unit:'t'},max:{value:10,unit:'t'}})),contractsAt:now(),used:new Set(),running:true,runId:'x',heartbeat:now(),order:{stake:1,duration:5,unit:'t'},rpc:{closed:false,request:async q=>{calls.push(q);if(q.proposal){if(deteriorate)for(let i=0;i<6;i++)add(-.3);return {echo_req:q,proposal:{id:'p',ask_price:1,payout:1.9}};}if(q.buy)return {buy:{contract_id:12,buy_price:1}};return {proposal_open_contract:{contract_id:12,is_sold:1,status:'won',profit:.9}};}}};service.contexts.set('x',c);await service.maybeExecute(c);assert.equal(calls.filter(q=>q.buy).length,deteriorate?0:1);const o=service.journal[0];assert.equal(o.state,deteriorate?'REJECTED':'SETTLED');if(!deteriorate){assert.equal(o.entryAnalysis.metrics.finalState,'READY');assert.ok(o.settlementAnalysis.metrics);assert.ok(o.proposalRequestedAt);}}});
