import {test} from 'node:test';
import assert from 'node:assert/strict';
import {TradabilityAuthority} from '../part-one-tradability.mjs';
import {PartOneExecution} from '../part-one-execution.mjs';
import {resetExecution} from '../execution-permission.mjs';
const flush=()=>new Promise(setImmediate);
function fixture(){let time=1000,epoch=0;const gate=new TradabilityAuthority({now:()=>time}),session={};gate.configure(session,{mode:'auto-block',windowSize:100,accountId:'demo',symbol:'R_100',revision:1});return {gate,session,feed:(pattern,n)=>{for(let i=0;i<n;i++)gate.tick('demo',{symbol:'R_100',quote:100+pattern[i%pattern.length]/100,pip_size:2,epoch:epoch+=2});},status:()=>gate.status(session,'demo','R_100','auto-block'),advance:n=>time+=n};}
test('server guard: warmup, NOT TRADABLE, continuous ticks and recovery',()=>{const f=fixture();assert.equal(f.status().allowed,false);f.feed([0,9],150);assert.equal(f.status().state,'NOT TRADABLE');assert.equal(f.status().allowed,false);f.feed([4,5],150);assert.equal(f.status().state,'TRADABLE');assert.equal(f.status().allowed,true);assert.equal(f.gate.watch('demo','R_100').engine.sequence,300);});
test('monitor is passive; AUTO BLOCK cannot bypass server with client monitor flag',()=>{const f=fixture();f.feed([0,9],150);assert.equal(f.gate.status(f.session,'demo','R_100','monitor').allowed,false);f.gate.configure(f.session,{mode:'monitor',windowSize:100,accountId:'demo',symbol:'R_100',revision:2});assert.equal(f.gate.status(f.session,'demo','R_100').allowed,true);});
test('stale ticks, missing precision, disconnect, mismatched symbol and pending config deny',()=>{const f=fixture();f.feed([4,5],150);assert.equal(f.status().allowed,true);f.advance(5001);assert.equal(f.status().allowed,false);f.feed([4,5],1);assert.equal(f.status().allowed,true);f.session.tradabilityPending=true;assert.equal(f.status().allowed,false);f.session.tradabilityPending=false;assert.equal(f.gate.status(f.session,'demo','R_10','auto-block').allowed,false);f.gate.tick('demo',{symbol:'R_100',quote:100.04,epoch:999});assert.equal(f.status().allowed,false);f.gate.disconnect('demo');assert.equal(f.status().allowed,false);});
test('window switches immediately to retained server metrics; reset revokes gate configuration',()=>{const f=fixture();f.feed([4,5],150);f.gate.configure(f.session,{mode:'auto-block',windowSize:500,accountId:'demo',symbol:'R_100',revision:2});assert.equal(f.status().sample,150);assert.equal(f.status().allowed,false);assert.throws(()=>f.gate.configure(f.session,{mode:'monitor',windowSize:100,revision:2}));resetExecution(f.session);assert.equal(f.status().allowed,false);assert.equal(f.gate.status(f.session,'demo','R_100').allowed,true);});
class Socket{readyState=1;sent=[];listeners={};addEventListener(n,f){(this.listeners[n]??=[]).push(f);}send(x){this.sent.push(JSON.parse(x));}reply(req,data){for(const f of this.listeners.message??[])f({data:JSON.stringify({req_id:req.req_id,...data})});}}
const request={attemptId:'tradability-test',type:'DIGITOVER',symbol:'R_100',stake:1,currency:'USD',mode:'manual'};
test('late proposal cannot BUY after tradability turns NOT TRADABLE',async()=>{const f=fixture();f.feed([4,5],150);const socket=new Socket(),execution=new PartOneExecution({connect:async()=>socket,setTimer:()=>0,clearTimer(){}});const flow=execution.execute({accountId:'demo',accountType:'demo'},{...request,authorizePurchase:()=>f.status().allowed});await flush();const p=socket.sent.find(r=>r.proposal);assert.ok(p);f.feed([0,9],150);socket.reply(p,{proposal:{id:'p',ask_price:1,payout:1.1}});await assert.rejects(flow.entry);assert.equal(socket.sent.filter(r=>r.buy).length,0);});
test('already purchased contract settles normally even after tradability blocks new entries',async()=>{const f=fixture();f.feed([4,5],150);const socket=new Socket(),execution=new PartOneExecution({connect:async()=>socket,setTimer:()=>0,clearTimer(){}});const flow=execution.execute({accountId:'demo',accountType:'demo'},{...request,authorizePurchase:()=>f.status().allowed});await flush();socket.reply(socket.sent.find(r=>r.proposal),{proposal:{id:'p',ask_price:1,payout:1.1}});socket.reply(socket.sent.find(r=>r.buy),{buy:{contract_id:123,buy_price:1}});await flow.entry;f.feed([0,9],150);assert.equal(f.status().allowed,false);socket.reply(socket.sent.find(r=>r.proposal_open_contract),{proposal_open_contract:{contract_id:123,is_sold:1,status:'won',profit:.1,payout:1.1,entry_tick:100.03,exit_tick:100.07}});const result=await flow.settlement;assert.equal(result.status,'won');assert.equal(socket.sent.filter(r=>r.buy).length,1);assert.equal(execution.snapshot('demo').blocking,false);});
